#!/usr/bin/env php
<?php
$timeout = 300;

print("vehje käynnistyi\n");

while (true) {
    print("poll\n");
    
    $last = json_decode(`journalctl -t deadman _TRANSPORT=syslog -n 1 -o json`);
    $last_ts = intdiv($last->_SOURCE_REALTIME_TIMESTAMP, 1000000);
    $left = $last_ts - time() + $timeout;

    if ($left < 0) {
        print("NAKS!\n");
        break;
    }

    sleep($left);
}
